spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/new_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 489392
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  devtools:
      restart:
        enabled: true
        additional-paths:
          - src/main/resources/templates
          - src/main/resources/static
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

